# Generated by Django 4.0.3 on 2022-05-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_user_name_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='e_mail',
        ),
    ]
